apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.2-alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
      volumes:
        - name: nginx-config
          hostPath:
            path: /home/sgal/nginx/nginx.conf
            type: File

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 8083
      targetPort: 8083
  type: LoadBalancer
